# Generated by Django 5.0.2 on 2025-12-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='store',
            field=models.CharField(choices=[('kabum', 'Kabum'), ('amazon', 'Amazon'), ('pichau', 'Pichau'), ('terabyte', 'Terabyte'), ('aliexpress', 'AliExpress'), ('outro', 'Outro')], default='kabum', max_length=100),
        ),
    ]
