# Generated by Django 5.0.2 on 2025-12-13 20:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_normalize_store_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='interest_free',
            field=models.BooleanField(default=True, help_text='Parcelamento sem juros'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('pc', 'PC / Setup Gamer'), ('casa', 'Casa / Decoração'), ('eletro', 'Eletrodomésticos'), ('moveis', 'Móveis'), ('eletronicos', 'Eletrônicos'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='fixed_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gastos fixos mensais (aluguel, contas, etc)', max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='safety_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Margem de segurança em porcentagem (padrão 10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('gpu', 'Placa de Vídeo'), ('cpu', 'Processador'), ('ram', 'Memória RAM'), ('ssd', 'SSD/HD'), ('motherboard', 'Placa Mãe'), ('psu', 'Fonte'), ('case', 'Gabinete'), ('cooler', 'Cooler'), ('monitor', 'Monitor'), ('keyboard', 'Teclado'), ('mouse', 'Mouse'), ('headset', 'Headset'), ('chair', 'Cadeira'), ('desk', 'Mesa'), ('sofa', 'Sofá'), ('tv', 'TV'), ('geladeira', 'Geladeira'), ('fogao', 'Fogão'), ('maquinalavar', 'Máquina de Lavar'), ('outro', 'Outro')], default='outro', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='store',
            field=models.CharField(choices=[('kabum', 'Kabum'), ('amazon', 'Amazon'), ('pichau', 'Pichau'), ('terabyte', 'Terabyte'), ('aliexpress', 'AliExpress'), ('mercadolivre', 'Mercado Livre'), ('magazineluiza', 'Magazine Luiza'), ('outro', 'Outro')], default='kabum', max_length=100),
        ),
    ]
